#config路径下的application.yml 比resources下的application.yml优先级更高
##1.多环境配置--多Profile文件模式
##默认配置
#server:
#  port: 8080
#  servlet:
#    context-path: /luohao1
##切换配置
#spring:
#  profiles:
#    active: dev #激活开发环境配置
#
#
##2.多环境配置--多Profile文档块模式
###默认配置
##server:
##  port: 8080
###切换配置
##spring:
##  profiles:
##    active: test
##---
###开发环境
##server:
##  port: 8081
##spring:
##  config:
##    activate:
##      on-profile: dev
##---
###测试环境
##server:
##  port: 8083
##spring:
##  config:
##    activate:
##      on-profile: test
##---
###生产环境
##server:
##  port: 8082
##spring:
##  config:
##    activate:
##      on-profile: prod