#1.多环境配置--多Profile文件模式
#默认配置
#server:
#  port: 8080
#  servlet:
#    context-path: /luohao
#切换配置
#spring:
#  profiles:
#    active: dev #激活开发环境配置


#2.多环境配置--多Profile文档块模式
#默认配置
################################################## springboot配置 ##########################################

server:
  port: 8080
  servlet:
    context-path: /luohao/

#切换配置
spring:
  profiles:
    active: dev
#配置静态资源路径，默认静态资源路径可以ctrl + 点击static-locations查看，一旦配置了，默认路径就会失效
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/imgs/
#配置国际化资源文件路径
  messages:
    basename: i18n.login
#开启restful风格
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#配置统一时间格式
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
#配置文件上传和下载的文件大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#当遇到同样名字的bean，是否允许覆盖
  main:
    allow-bean-definition-overriding: true
#配置热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

################################################## 数据源连接信息 ##########################################

  datasource:
    username: root
    password: 815421
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver



################################################## Druid连接池的配置 ##########################################
    druid:
      initial-size: 5                                                                 #初始化连接大小
      min-idle: 5                                                                     #最小连接池数量
      max-active: 20                                                                  #最大连接池数量
      max-wait: 60000                                                                 #获取连接时最大等待时间，单位毫秒
      time-between-eviction-runs-millis: 60000                                        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000                                          #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL                                            #测试连接
      test-while-idle: true                                                           #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-on-borrow: false                                                           #获取连接时执行检测，建议关闭，影响性能
      test-on-return: false                                                           #归还连接时执行检测，建议关闭，影响性能
      pool-prepared-statements: false                                                 #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      max-pool-prepared-statement-per-connection-size: 20                             #开启poolPreparedStatements后生效
      filters: stat,wall                                                              #配置扩展插件，常用的插件有=>stat:监控统计  wall:防御sql注入
      connection-properties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000' #通过connectProperties属性来打开mergeSql功能;慢SQL记录

###################################################### Druid 监控配置信息  ##########################################
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true                                                                 #是否开启内置监控页面，默认值为 false
        url-pattern: '/druid/*'                                                       #StatViewServlet 的映射路径，即内置监控页面的访问地址
        reset-enable: true                                                            #是否启用重置按钮
        login-username: root                                                         #内置监控页面的登录页用户名 username
        login-password: root                                                         #内置监控页面的登录页密码 password
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true                                                                 #是否开启内置监控中的 Web-jdbc 关联监控的数据
        url-pattern: '/*'                                                             #匹配路径
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'                     #排除路径
        session-stat-enable: true                                                     #是否监控session
      # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
      aop-patterns: com.luohao.springboot.*                                               #Spring监控AOP切入点，如x.y.z.abc.*,配置多个英文逗号分隔
      # 对配置已开启的 filters 即 stat(sql 监控)  wall（防火墙）
      filter:
        #配置StatFilter (SQL监控配置)
        stat:
          enabled: true                                                               #开启 SQL 监控
          slow-sql-millis: 1000                                                       #慢查询
          log-slow-sql: true                                                          #记录慢查询 SQL
        #配置WallFilter (防火墙配置)
        wall:
          enabled: true                                                               #开启防火墙
          config:
            update-allow: true                                                        #允许更新操作
            drop-table-allow: false                                                   #禁止删表操作
            insert-allow:  true                                                       #允许插入操作
            delete-allow: true                                                        #删除数据操作
################################################## Redis配置 ##########################################
  redis:                  #springboot2.x版本，其内置的Redis中间件不再是Jedis，而是换成了lettuce
    host: 192.168.213.60  #ip地址
    port: 6379            #端口号
    password: root        #密码
    database: 0           #数据库名，0~15
    timeout: 2000         #连接超时时长，单位：毫秒



###################################### MyBatis 配置 ######################################
mybatis:
  # 指定 mapper.xml 的位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
  type-aliases-package: com.luohao.springboot.bean
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true
    #开启Mybatis日志输出，可以看到执行的sql语句和结果
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

###################################### pagehelper分页插件配置 ######################################
pagehelper:
  helper-dialect: mysql


###################################### 多场景切换配置 ######################################

---
#开发环境
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: dev

---
#测试环境
server:
  port: 8083
spring:
  config:
    activate:
      on-profile: test
---
#生产环境
server:
  port: 8082
spring:
  config:
    activate:
      on-profile: prod